# Generated by Django 3.0.3 on 2020-02-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('facebook_url', models.CharField(max_length=500)),
                ('opening_hours', models.CharField(max_length=500)),
                ('mondays_food', models.CharField(max_length=500)),
                ('mondays_entertainment', models.CharField(max_length=500)),
                ('mondays_other', models.CharField(max_length=500)),
            ],
        ),
    ]
