# Generated by Django 3.0.3 on 2020-02-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_business_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='main_img',
            new_name='b_image',
        ),
    ]
