# Generated by Django 3.0.3 on 2020-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200218_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
        migrations.AlterField(
            model_name='business',
            name='b_image',
            field=models.ImageField(upload_to='main/static'),
        ),
    ]
