# Generated by Django 3.0.3 on 2020-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200218_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='locality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='postal_code',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='street_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='business',
            name='street_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
