# Generated by Django 3.0.7 on 2020-08-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_specialevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 21, 5, 22, 814827)),
            preserve_default=False,
        ),
    ]
